-- Drop the function 'FN_OnlyYear' in schema 'dbo'
IF EXISTS (
SELECT *
FROM INFORMATION_SCHEMA.ROUTINES
WHERE SPECIFIC_SCHEMA = N'dbo'
    AND SPECIFIC_NAME = N'FN_OnlyYear'
)
DROP FUNCTION dbo.[FN_OnlyYear]
GO